#!/bin/sh

prefix=/usr/local
SHARE=$prefix/share/house

HAPP=houseportal

case $1 in
    remove)
        systemctl daemon-reload
        ;;
    purge)
        systemctl daemon-reload
        rm -f /etc/default/$HAPP /etc/house/portal.config
        ;;
esac

